### PR TITLE
Join the Stream and Verbose flags into verbosity

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Comment by come-maiz** [comment]
Requires #2.

**Comment by fgimenez** [comment]
Looks good, I don't like too much the use of the literals 1 and 2 for the verbosity level instead of constants. 

IMO it would be better to define a type as an alias of uint8 (for example, VerbosityLevel), then declare constants for the two levels with iota. 

If we add more levels in the future we'll need to change the code anyway to take into account the new numbers and all the functions will be clearer when comparing the verbosity variable and constants with meaningful names, what do you think?

**Comment by come-maiz** [comment]
yes, I'll do that when I'm back. How would you name the levels?

**Comment by fgimenez** [comment]
We have three of them, beginning with 0, right? No idea, in fact it's a bit hard to find good names. I'm not sure if they are related to each other as incremental, for 1 and 2 they seem to add different things, maybe each comparison should be done with an equal instead of greater/lower than... Anyway, I think that any name will do, we can come back to this later.

**Comment by come-maiz** [comment]
I will take your last suggestion and report it as a bug. The last branch of this set plays a little with levels, and it will be easier if we land it before making this change. I'll do it first thing after the other branch. I propose QUIET, LOW and HIGH

**Comment by fgimenez** [comment]
Sorry for not being clear :) I was suggesting to use whatever name in the constants to replace the literals and come back to it later. 

It would be also good to use names that don't imply increasing verbosity because it seems that, by merging the two separate variables into one, the intention of both are merged too, and for instance according to the unit tests level 0 doesn't print anything, level 1 prints the most and level 2 is in the middle, please correct me if I'm wrong. Anyway, we can handle it while addressing the issue.

**Comment by come-maiz** [comment]
hum, I didn't notice that the tests need to be renamed.
And no, 2 should be the most verbose one. 1 should be like -v, and 2 like -vv. Maybe there's something not so clear in the tests, the rename will make it better.

**Pull request merged**
